lab3_ts/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('', include('paynting.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paynting/forms.py
from betterforms.multiform import MultiModelForm
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Masterpiece, MadeWith, Sort, Profile


class MasterpieceForm(forms.ModelForm):
    class Meta:
        model = Masterpiece
        fields = ['masterpiece_name', 'image', 'description']

    def save_user(self, commit=True):
        objects = super(MasterpieceForm, self).save(commit=False)

        if commit:
            uploaded_by = objects['uploaded_by']
            print(uploaded_by)
            uploaded_by.save()
            masterpiece = objects
            masterpiece.uploaded_by = uploaded_by
            masterpiece.save()


class MadeWithForm(forms.ModelForm):
    class Meta:
        model = MadeWith
        fields = ['hardware', 'software']


class MasterpieceUpdateForm(forms.ModelForm):
    class Meta:
        model = Masterpiece
        fields = ['masterpiece_name', 'image', 'description']


class MasterpieceUpdateMultiForm(MultiModelForm):
    form_classes = {
        'masterpiece': MasterpieceUpdateForm,
        'made_with': MadeWithForm,
    }


class MasterpieceCreationMultiForm(MultiModelForm):
    form_classes = {
        'masterpiece': MasterpieceForm,
        'made_with': MadeWithForm,
    }

    def save_user(self, user):
        objects = super(MasterpieceCreationMultiForm, self).save(commit=False)
        objects['masterpiece'].save_user(user)

    def save_made_with(self, made_with):
        objects = super(MasterpieceCreationMultiForm, self).save(commit=False)
        objects['masterpiece'].save_made_with(made_with)


SORT_TYPES = (
    ('az', 'A to Z'),
    ('za', 'Z to A'),
)


class SortForm(forms.ModelForm):
    sort_type = forms.ChoiceField(choices=SORT_TYPES, required=False)

    class Meta:
        model = Sort
        fields = ['sort_type']


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, help_text='Last Name')
    last_name = forms.CharField(max_length=100, help_text='Last Name')
    email = forms.EmailField(max_length=150, help_text='Email')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['signup_confirmation']

templates/account.html
{% extends 'base.html' %}

{% if not user.is_authenticated %}
    <meta http-equiv="refresh" content="0; url = /"/>
{% endif %}

{% block content %}

    <div class="container">
        <h2>About {{ user.username }}</h2>
        <p>Email: {{ user.email }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>

        <hr>
        <h3>Masterpieces by {{ user.username }}</h3>
        <div class="row">
            {% for masterpiece in masterpiece_list %}
                {% if masterpiece.uploaded_by == user %}
                    <div class="col s4">
                        <div class="card">
                            <div class="card-image">
                                <a href="{{ masterpiece.get_absolute_url }}">
                                    <img src="{{ masterpiece.image.url }}" alt="{{ masterpiece.masterpiece_name }}">
                                </a>
                            </div>
                            <div class="card-content">
                                <p>{{ masterpiece.masterpiece_name }}</p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

{% endblock %}

{% block logout %}

    <a href="{% url 'logout' %}">Log out</a>

{% endblock %}

templates/activation_request.html
{% autoescape off %}
    Hi {{ user.username }} (email: {{ user.email }},

    Please click the following link to confirm your registration:
    http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/activation_sent.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h3>Activation link sent! Please check your terminal or email.</h3>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Paynting</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav>
    <div class="container nav-wrapper">
        <a href="/" class="brand-logo">Paynting</a>
        <ul id="nav-mobile" class="right">
            <li>
                <a href="/account/{{ user.username }}">
                    {% block logout %}
                        {% if user.is_authenticated %}
                            Hi, {{ user.username }}!
                        {% else %}
                            <ul id="nav-mobile" class="right hide-on-med-and-down">
                                <li><a href="{% url 'login' %}">Log in</a></li>
                                <li><a href="{% url 'signup' %}">Sign up</a></li>
                            </ul>
                        {% endif %}
                    {% endblock %}
                </a>
            </li>
        </ul>
    </div>
</nav>

{% block masterpiece_detail %}
    {% block content %}
        <div class="container">
            <h1 style="text-align: left">Discover the world’s top designers & creatives</h1>
            <div class="row">
                <div class="col s4">
                    <div class="center">
                        <i class="large material-icons" style="color: #B0D0D3">flash_on</i>
                        <p>Fast</p>
                        <p class="light center">With a beautiful GUI.</p>
                    </div>
                </div>

                <div class="col s4">
                    <div class="center">
                        <i class="large material-icons" style="color: #F7E3AF">explore</i>
                        <p>Masterpieces from all around the world</p>
                        <p class="light center">Best of the best</p>
                    </div>
                </div>

                <div class="col s4">
                    <div class="center">
                        <i class="large material-icons" style="color: #F7AF9D">whatshot</i>
                        <p>Alternative for Dribbble</p>
                        <p class="light center">Built with ❤️ (actually with 🤬)</p>
                    </div>
                </div>
            </div>

            <form action="{% url 'search' %}" method="get">
                <input name="q" type="text" placeholder="What are you looking for?">
            </form>

            <div style="text-align: center">
                <a href="/sort">
                    <button class="btn waves-effect waves-light" type="submit" name='register_btn' }>
                        I WANT TO SORT ALL OF THIS
                    </button>
                </a>
            </div>

            <div class="row">
                {% for masterpiece in masterpiece_list %}
                    <div class="col s4">
                        <div class="card">
                            <div class="card-image">
                                <a href="{{ masterpiece.get_absolute_url }}">
                                    <img src="{{ masterpiece.image.url }}" alt="{{ masterpiece.masterpiece_name }}">
                                </a>
                            </div>
                            <div class="card-content">
                                <p>{{ masterpiece.masterpiece_name }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endblock %}

    {% if user.is_authenticated %}
        <div class="fixed-action-btn">
            <a href="/masterpiece/create" class="btn-floating btn-large red">
                <i class="large material-icons">add</i>
            </a>
        </div>
    {% endif %}
{% endblock %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</body>
</html>

templates/create.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        {% if user.is_authenticated %}
            <h1>Add your masterpiece</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" id="id_masterpiece-uploaded_by" name="id_masterpiece-uploaded_by"
                       value={{ user.username }}>
                <div style="text-align:center">
                    <button class="btn waves-effect waves-light" type="submit" }>Submit</button>
                </div>
            </form>
        {% else %}
            <h2>Sorry, you can't do it</h2>
        {% endif %}
    </div>

{% endblock %}

templates/masterpiece.html
{% extends 'base.html' %}

{% load static %}

{% block masterpiece_detail %}

    <div class="container" style="text-align: center">
        <h2>{{ masterpiece.masterpiece_name }}</h2>
    </div>

    <div class="container">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <div id="image">
            <img src="{{ masterpiece.image.url }}" alt="{{ masterpiece.image }}" width="500">
        </div>

        <div id="text">
            <p><b>By:</b> {{ masterpiece.uploaded_by }}</p>
            <p><b>Description:</b> {{ masterpiece.description }}</p>
            {% if masterpiece.made_with != None %}
                <p><b>Hardware that were used:</b> {{ masterpiece.made_with.hardware }}</p>
                <p><b>Software that were used:</b> {{ masterpiece.made_with.software }}</p>
            {% endif %}
        </div>
    </div>

    {% if user.is_authenticated %}
        {% if masterpiece.uploaded_by == user %}
            <div class="fixed-action-btn">
                <a href="/masterpiece/{{ masterpiece.id }}/update/" class="btn-floating btn-large red">
                    <i class="large material-icons">edit</i>
                </a>
            </div>
            <div id="delete_button">
                <div class="fixed-action-btn" style="right: 96px;">
                    <a href="/masterpiece/{{ masterpiece.id }}/delete/" class="btn-floating btn-large red">
                        <i class="large material-icons">delete</i>
                    </a>
                </div>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            {% for masterpiece in masterpiece_list %}
                <div class="col s4">
                    <div class="card">
                        <div class="card-image">
                            <a href="{{ masterpiece.get_absolute_url }}">
                                <img src="{{ masterpiece.image.url }}" alt="{{ masterpiece.masterpiece_name }}">
                            </a>
                        </div>
                        <div class="card-content">
                            <p>{{ masterpiece.masterpiece_name }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h2>Sign up</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn waves-effect waves-light" type="submit" name='register_btn' }>
                Sign up
            </button>
        </form>
    </div>
{% endblock %}

templates/sort.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form method="get">
            <select id="id_sort_type" name="sort_type" class="browser-default">
                <option value="az">A to Z</option>
                <option value="za">Z to A</option>
            </select>
            <button class="btn waves-effect waves-light" type="submit" }>
                Submit
            </button>
        </form>

        <div class="row">
            {% for masterpiece in masterpieces_sorted %}
                <div class="col s4">
                    <div class="card">
                        <div class="card-image">
                            <a href="{{ masterpiece.get_absolute_url }}">
                                <img src="{{ masterpiece.image.url }}" alt="{{ masterpiece.masterpiece_name }}">
                            </a>
                        </div>
                        <div class="card-content">
                            <p>{{ masterpiece.masterpiece_name }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}